#pragma config(Motor,  motor1,          LeftDrive,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor2,          RightDrive,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor6,          Convayor,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor7,          FrontClaw,     tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor8,          BackLock,      tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

string ConvayorDir = "off";

void StartConvayor(){
	if (vexRT[BtnLUp] == 1) {
		if (ConvayorDir == "up"){
			stopMotor(Convayor);
			ConvayorDir = "off";
		} else {
			ConvayorDir = "up";
			setMotor(Convayor, 100);
		}
	}
	if (vexRT[BtnLDown] == 1) {
		if (ConvayorDir == "down"){
			stopMotor(Convayor);
			ConvayorDir = "off";
		} else {
			ConvayorDir = "down";
			setMotor(Convayor, -100);
		}
	}
	sleep(200);
}


task main()
{
	//setMotorCurrentLimit(FrontClaw, 500);
	//setMotorCurrentLimit(BackLock, 400);
	repeat(forever){
		StartConvayor();
		tankControl(ChD,ChA, 0);
		armControl(FrontClaw, BtnRUp, BtnRDown, 100);
		armControl(BackLock,BtnFUp,BtnFDown,100);
		//if(getBumperValue(Button) == 1) {
			//setMotorCurrentLimit(FrontClaw, 300);
			//setMotorBrakeMode(FrontClaw, motorHold);
		//};
		displayCenteredTextLine(0,"LeftMotor: %d", getMotorCurrent(LeftDrive));
    displayCenteredTextLine(1,"RightMotor: %d", getMotorCurrent(RightDrive));
    displayCenteredTextLine(2,"FrontClaw: %d", getMotorCurrent(FrontClaw));
    displayCenteredTextLine(3,"ConvayorMotor: %d", getMotorCurrent(Convayor));
    displayCenteredTextLine(4,"BackLockMotor: %d", getMotorCurrent(BackLock));

	}
}
