#pragma config(Sensor, port12,  LED,            sensorVexIQ_LED)
#pragma config(Motor,  motor1,          LeftDrive,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor2,          RightDrive,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor6,          Convayor,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor7,          FrontClaw,     tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor8,          BackLock,      tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//The circomfrince of the wheel is 7.85
// 1 rotation is 7.85 inches
// 1 rotation is 360 degrees

void forwardMove(int distance, int speed){
	moveMotorTarget(motor1, distance, speed);
  moveMotorTarget(motor2, distance, speed);
  //Holds program flow until the motor on port 1 comes to a complete stop.
  waitUntilMotorStop(motor1);
  waitUntilMotorStop(motor2);
}
void backwardMove(int distance, int speed){
	moveMotorTarget(motor1, -distance, -speed);
  moveMotorTarget(motor2, -distance, -speed);
  //Holds program flow until the motor on port 1 comes to a complete stop.
  waitUntilMotorStop(motor1);
  waitUntilMotorStop(motor2);
}
void turnRightDist(int distance,int Speed){
  moveMotorTarget(motor1, distance, Speed);
	moveMotorTarget(motor2, -distance, -Speed);
	waitUntilMotorStop(motor1);
	waitUntilMotorStop(motor2);
}
void turnLeftDist(int distance,int Speed){
  moveMotorTarget(motor1, -distance, -Speed);
	moveMotorTarget(motor2, distance, Speed);
	waitUntilMotorStop(motor1);
	waitUntilMotorStop(motor2);
}

task main()
{
	
//Grab the first 
	moveMotorTarget(FrontClaw, -1000, -100);
	//waitUntilMotorStop
	//stopMotor(FrontClaw);
	turnRightDist(100,60);
  forwardMove(270,30);
  turnLeftDist(175,60);
  forwardMove(90,30);
  moveMotorTarget(FrontClaw, 1000, 100);
  forwardMove(195, 30);
  turnRightDist(75,40);
  forwardMove(300,50);
	moveMotorTarget(FrontClaw, -300, -50);
	waitUntilMotorStop(FrontClaw);
	backwardMove(200,50);

}
