#pragma config(Sensor, port12,  LED,            sensorVexIQ_LED)
#pragma config(Motor,  motor1,          LeftDrive,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor2,          RightDrive,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor6,          Convayor,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor7,          FrontClaw,     tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor8,          BackLock,      tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//The circomfrince of the wheel is 7.85
// 1 rotation is 7.85 inches
// 1 rotation is 360 degrees

void forwardMove(int distance, int speed){
	moveMotorTarget(motor1, distance, speed);
  moveMotorTarget(motor2, distance, speed);
  //Holds program flow until the motor on port 1 comes to a complete stop.
  waitUntilMotorStop(motor1);
  waitUntilMotorStop(motor2);
}
void backwardMove(int distance, int speed){
	moveMotorTarget(motor1, -distance, -speed);
  moveMotorTarget(motor2, -distance, -speed);
  //Holds program flow until the motor on port 1 comes to a complete stop.
  waitUntilMotorStop(motor1);
  waitUntilMotorStop(motor2);
}
void turnRightDist(int distance,int Speed){
  moveMotorTarget(motor1, distance, Speed);
	moveMotorTarget(motor2, -distance, -Speed);
	waitUntilMotorStop(motor1);
	waitUntilMotorStop(motor2);
}
void turnLeftDist(int distance,int Speed){
  moveMotorTarget(motor1, -distance, -Speed);
	moveMotorTarget(motor2, distance, Speed);
	waitUntilMotorStop(motor1);
	waitUntilMotorStop(motor2);
}

//Grab the first GREEN BOX
void firstGreen(){
	moveMotorTarget(FrontClaw, -1000, -100);
	turnRightDist(100,60);
  forwardMove(280,30);
  turnLeftDist(168,60);
  wait(.2, seconds);
  forwardMove(130,30);
  moveMotorTarget(FrontClaw, 1000, 100);
  forwardMove(170, 30);
  wait(.2, seconds);
  turnRightDist(70,40);
  wait(.2, seconds);
  forwardMove(230,50);
	moveMotorTarget(FrontClaw, -250, -50);
	waitUntilMotorStop(FrontClaw);
	wait(.2, seconds);
	backwardMove(215,50);
}

//Grab the second Green Box
void secondGreen(){
	forwardMove(370,30);
  turnRightDist(146,40);
	wait(.2, seconds);
	moveMotorTarget(FrontClaw, -1000, -100);
	forwardMove(330,30);
	moveMotorTarget(FrontClaw, 500, 50);
	wait(.3, seconds);
	forwardMove(180,30);
	turnRightDist(145,30);
	wait(.2, seconds);
	forwardMove(220,30);
	moveMotorTarget(FrontClaw, -50, -50);
}

//Grab the third green box
void thridGreen(){
	moveMotorTarget(FrontClaw, -1000, -100);
	turnLeftDist(100,60);
  forwardMove(280,30);
  turnRightDist(168,60);
  wait(.2, seconds);
  forwardMove(130,30);
  moveMotorTarget(FrontClaw, 1000, 100);
  forwardMove(170, 30);
  wait(.2, seconds);
  turnLeftDist(70,40);
  wait(.2, seconds);
  forwardMove(230,50);
	moveMotorTarget(FrontClaw, -250, -50);
	waitUntilMotorStop(FrontClaw);
	backwardMove(215,50);
	wait(1, seconds);
}

task main()
{
	setTouchLEDColor(LED, colorRed);
	waitUntil(getTouchLEDValue(LED) == 1);
	setTouchLEDColor(LED, colorGreen);
	firstGreen();
	setTouchLEDColor(LED, colorRed);
	waitUntil(getTouchLEDValue(LED) == 1);
	setTouchLEDColor(LED, colorGreen);
	secondGreen();
	setTouchLEDColor(LED, colorRed);
	waitUntil(getTouchLEDValue(LED) == 1);
	setTouchLEDColor(LED, colorGreen);
	thridGreen();

	int counter = 0;
	repeat(255) {
		setTouchLEDHue(LED, counter);
		sleep(30);
		counter =  counter + 1;
	}
}
// setMotor(Convayor, -80);
