
#pragma config(Motor,  motor4,          FrontClaw,     tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor5,          RightDrive,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor6,          Convayor,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Sensor, port10,  LED,            sensorVexIQ_LED)
#pragma config(Motor,  motor11,          LeftDrive,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor12,          BackLock,      tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//The circomfrince of the wheel is 7.85
// 1 rotation is 7.85 inches
// 1 rotation is 360 degrees

void forwardMove(int distance, int speed){
	moveMotorTarget(LeftDrive, distance, speed);
  moveMotorTarget(RightDrive, distance, speed);
  //Holds program flow until the motor on port 1 comes to a complete stop.
  waitUntilMotorStop(LeftDrive);
  waitUntilMotorStop(RightDrive);
}
void backwardMove(int distance, int speed){
	moveMotorTarget(LeftDrive, -distance, -speed);
  moveMotorTarget(RightDrive, -distance, -speed);
  //Holds program flow until the motor on port 1 comes to a complete stop.
  waitUntilMotorStop(LeftDrive);
  waitUntilMotorStop(RightDrive);
}
void turnRightDist(int distance,int Speed){
  moveMotorTarget(LeftDrive, distance, Speed);
	moveMotorTarget(RightDrive, -distance, -Speed);
	waitUntilMotorStop(LeftDrive);
	waitUntilMotorStop(RightDrive);
}
void turnLeftDist(int distance,int Speed){
  moveMotorTarget(LeftDrive, -distance, -Speed);
	moveMotorTarget(RightDrive, distance, Speed);
	waitUntilMotorStop(LeftDrive);
	waitUntilMotorStop(RightDrive);
}

//Grab the first GREEN BOX
void firstGreen(){
	moveMotorTarget(FrontClaw, -1000, -100);
	forwardMove(5,50);
	turnRightDist(100,60);
  forwardMove(275,30);
  turnLeftDist(165,60);
  sleep(200);
  forwardMove(230,30);
//	waitUntilMotorStop(LeftDrive);
  moveMotorTarget(FrontClaw, 900, 50);
	//waitUntilMotorStop(FrontClaw);
  forwardMove(200, 30);
  sleep(200);
  turnRightDist(60,40);
  sleep(200);
  forwardMove(175,50);
	moveMotorTarget(FrontClaw, -400, -50);
	waitUntilMotorStop(FrontClaw);
	sleep(200);
	//forwardMove(40,50);
	backwardMove(500,50);
}

//Grab the second Green Box
void secondGreen(){
//	forwardMove(360,30);
  turnRightDist(146,40);
  forwardMove(225,30);
  turnLeftDist(80,40);
	sleep(200);
	moveMotorTarget(FrontClaw, -1000, -100);
	forwardMove(250,30);
//  turnLeftDist(50,40);
	moveMotorTarget(FrontClaw, 1000, 50);
	sleep(600);
	backwardMove(125,30);
	sleep(600);
  turnRightDist(140, 40);
	forwardMove(60,30);
//	turnRightDist(145,30);
	sleep(200);
//	forwardMove(218,30);
	moveMotorTarget(FrontClaw, -220, -50);
	waitUntilMotorStop(FrontClaw);
	backwardMove(200,70);
}

//Grab the third green box
void thridGreen(){
	moveMotorTarget(FrontClaw, -1000, -100);
	turnLeftDist(90,60);
  forwardMove(270,30);
  turnRightDist(155,60);
  sleep(200);
  forwardMove(150,30);
  sleep(100);
  moveMotorTarget(FrontClaw, 1000, 100);
  forwardMove(200, 30);
  sleep(200);
  turnLeftDist(66,40);
  sleep(200);
  forwardMove(198,50);
	moveMotorTarget(FrontClaw, -400, -50);
	waitUntilMotorStop(FrontClaw);
	forwardMove(4,50);
	backwardMove(215,50);
	sleep(700);
}

void blueCubes(){
	///pick up blues
	moveMotorTarget(FrontClaw, -450, -50);
  turnRightDist(135,40);
	sleep(200);
	forwardMove(350,50);
  turnLeftDist(140,40);
	sleep(200);
	forwardMove(150,50);
  moveMotorTarget(FrontClaw, 500, 100);
  sleep(300);
	backwardMove(250,50);
  turnLeftDist(10,40);
  sleep(200);
	backwardMove(60,20);
  //moveMotorTarget(BackLock, -300, 100);
  sleep(500);
  ///move accross field
  turnLeftDist(60,40);
  sleep(200);
	forwardMove(150,50);
  turnLeftDist(70,40);
  sleep(200);
	forwardMove(50,50);
  turnLeftDist(10,40);
	forwardMove(800,50);
  ///place blues
  turnLeftDist(60,40);
  moveMotorTarget(FrontClaw, -300, 100);
	forwardMove(450,50);
  //moveMotorTarget(FrontClaw, -150, 100);
  turnRightDist(5,100);
  forwardMove(280,50);
	moveMotorTarget(FrontClaw, -150, 100);
	waitUntilMotorStop(FrontClaw);
	backwardMove(250,50);
  turnLeftDist(126,40);
	backwardMove(550,50);
  moveMotorTarget(BackLock, -150, 100);
	}

void waitForTouch(){
	setTouchLEDColor(LED, colorRed);
	waitUntil(getTouchLEDValue(LED) == 1);
	setTouchLEDColor(LED, colorGreen);
}

task main()
{
	waitForTouch();
	firstGreen();
//	setTouchLEDColor(LED, colorRed);
//	waitUntil(getTouchLEDValue(LED) == 1);
//	setTouchLEDColor(LED, colorGreen);
	secondGreen();
	waitForTouch();
	thridGreen();

	blueCubes();
	int counter = 0;
	repeat(255) {
		setTouchLEDHue(LED, counter);
		sleep(30);
		counter =  counter + 1;
	}
}
// setMotor(Convayor, -80);
