#pragma config(Sensor, port3,  Gyro,           sensorVexIQ_Gyro)
#pragma config(Sensor, port10, LED,            sensorVexIQ_LED)
#pragma config(Motor,  motor4,          FrontClaw,     tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor5,          RightDrive,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor6,          Convayor,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,         LeftDrive,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor12,         BackLock,      tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//The circomfrince of the wheel is 7.85
// 1 rotation is 7.85 inches
// 1 rotation is 360 degrees

void forwardMove(int distance, int speed){
	moveMotorTarget(LeftDrive, distance, speed);
	moveMotorTarget(RightDrive, distance, speed);
	//Holds program flow until the motor on port 1 comes to a complete stop.
	waitUntilMotorStop(LeftDrive);
	waitUntilMotorStop(RightDrive);
}
void backwardMove(int distance, int speed){
	moveMotorTarget(LeftDrive, -distance, -speed);
	moveMotorTarget(RightDrive, -distance, -speed);
	//Holds program flow until the motor on port 1 comes to a complete stop.
	waitUntilMotorStop(LeftDrive);
	waitUntilMotorStop(RightDrive);
}

void turnRightDist(float deg, int speed){
	int degToMove = (deg - 1);
	resetGyro(Gyro);
	motor[LeftDrive] = speed;
	motor[RightDrive] = -speed;
	waitUntil(getGyroDegreesFloat(Gyro) <= -degToMove);
	stopMotor(LeftDrive);
	stopMotor(RightDrive);
	if(getGyroDegreesFloat(Gyro) < -degToMove) {
		motor[LeftDrive] = -10;
		motor[RightDrive] = 10;
		waitUntil(getGyroDegreesFloat(Gyro) >= -degToMove);
		stopMotor(LeftDrive);
		stopMotor(RightDrive);
	}
}

void turnLeftDist(float deg, int speed){
	int degToMove = (deg - 1);
	resetGyro(Gyro);
	motor[LeftDrive] = -speed;
	motor[RightDrive] = speed;
	waitUntil(getGyroDegreesFloat(Gyro) >= degToMove);
	stopMotor(LeftDrive);
	stopMotor(RightDrive);

	if(getGyroDegreesFloat(Gyro) > degToMove) {
		motor[LeftDrive] = 10;
		motor[RightDrive] = -10;
		waitUntil(getGyroDegreesFloat(Gyro) <= degToMove);
		stopMotor(LeftDrive);
		stopMotor(RightDrive);
	}

}

void waitForTouch(){
	setTouchLEDColor(LED, colorRed);
	waitUntil(getTouchLEDValue(LED) == 1);
	setTouchLEDColor(LED, colorGreen);
}

void firstGreen(){
	motor[Convayor] = 100;
	backwardMove(65, 10);
	sleep(300);
	forwardMove(60, 10);
	sleep(300);
	//Get Red
	forwardMove(25,50);
	turnRightDist(103,50);
	moveMotorTarget(FrontClaw, -1000, -100);
	backwardMove(100,50);
	moveMotorTarget(BackLock, -400,50);
	backwardMove(70,10);
	backwardMove(192,50);   //originally 200
	//Get Green Middle
	turnLeftDist(48,50);    // originally 50 
	forwardMove(135,30);
	forwardMove(120,20);  //changed to 20
	moveMotorTarget(FrontClaw, 900, 50);
	forwardMove(150,20);  //change to 20
	turnRightDist(87,50);  //refining this angle  --- start 90
	forwardMove(465,50);   //Work on this distance  --- start 450
	moveMotorTarget(FrontClaw,-200,-30);
	waitUntilMotorMoveComplete(FrontClaw);
	forwardMove(20,50);
	moveMotorTarget(FrontClaw,-200,-30);
	backwardMove(60,50);  //working on this  -- currently 90

}

void secondGreen(){
	turnLeftDist(87,50);  //working  -- currently 90
	moveMotorTarget(FrontClaw,-1000,-1000);
	//waitUntilMotorMoveComplete(FrontClaw);
	sleep(600);
	forwardMove(175,30);
	moveMotorTarget(FrontClaw, 800, 50);
	forwardMove(250,50);  // perfecting this distance
	turnLeftDist(103,50);
	forwardMove(490,50);
	moveMotorTarget(FrontClaw,-400,-50);
	waitUntilMotorMoveComplete(FrontClaw);
	backwardMove(750,50);
	moveMotorTarget(BackLock, 300, 100);
	backwardMove(550, 100);
	forwardMove(100, 100);
	stopMotor(Convayor);

}

void getThirdGreen() {
	motor[Convayor] = 100;
	moveMotorTarget(FrontClaw, -1000, -100);
	forwardMove(12,50);

	turnLeftDist(90,50);
	forwardMove(300,30);  // orginally 290 
	turnRightDist(134,50);  //orginally 135
	forwardMove(190,30);   //originally 175
	moveMotorTarget(FrontClaw, 900, 50);
	forwardMove(245,20);   //originally 200
	turnLeftDist(47,30);
	forwardMove(235,50);
	//turnLeftDist(10,10);
	moveMotorTarget(FrontClaw,-400,-50);
	waitUntilMotorMoveComplete(FrontClaw);
	backwardMove(200,50);

	//Get Blue
	moveMotorTarget(FrontClaw,-400,-50);
	turnRightDist(90,50);  
	forwardMove(355,50);     //originally 270
	turnLeftDist(90,50);
	forwardMove(200,30);     //orginally 150 
	moveMotorTarget(FrontClaw, 700, 100);
	sleep(500);
	//Place Blue
	turnRightDist(45,50);  	
	backwardMove(300,50);
	turnLeftDist(135,50);
	forwardMove(1000,50); 
	turnLeftDist(35,50);
	moveMotorTarget(FrontClaw,-500,-100);	
	sleep(500);
	moveMotorTarget(FrontClaw,-300,-100);	
//	waitUntilMotorMoveComplete(FrontClaw);
	forwardMove(470,50);
	backwardMove(100,50);  //working on this  -- currently 90
	
	
}

task main()
{
	waitForTouch();
	firstGreen();
	secondGreen();
	waitForTouch();
	getThirdGreen();
}
